Dev/badges
mymadhead/testGuru pull request #34
Opened 2020-08-19 17:00 UTC by mymadhead

2020-08-20 04:51 UTC, max-underthesun commented on app/models/badge.rb
> +  validates_inclusion_of :rule_name, in: %w[first_try category level loser]
то что добавил эту валидацию - очень правильно
но ))
я бы скорее сохранил константу с набором правил в сервисе, а в модели бы оставил только валидацию, что правило входит в список возможных правил (вот эту)
почему?
потому что, если правила будут добавляться, то код будет добавляться в сервис (новые методы)
там же сразу можно будет в константу дописать имена этих новых правил
модель при этом трогать не придется, все будет работать как прежде
если есть возможность локализовать "потенциальные изменения" в одной точке и не разносить "код, который может иземениться" по нескольким классам, то это почти всегда нужно делать

2020-08-20 04:51 UTC, max-underthesun commented on app/models/badge.rb
> +  has_many :badges_users, dependent: :delete_all
опция `dependent: :delete_all` редко используется, потому что она удаляет прямиком из базы, минуя логику моделей
если нет каких-то специальных причин для использования именно `delete_all`, то в большинстве случаев лучше заменить эту опцию на `dependent: :destroy`

2020-08-20 04:51 UTC, max-underthesun commented on app/services/awarder.rb
> +    @user.badges_users.where(badge: Badge.where(rule_name: rule_name, rule_value: rule_value))
чтобы не искать здесь заново бейдж в базе по его аттрибутам передай в метод проверки целиком бейдж из метода `call`, и потом целиком сюда, тогда здесь будет: `where(badge: badge)`
и не придется `rule_name` передавать

2020-08-20 04:51 UTC, max-underthesun commented on app/services/awarder.rb
> +                                              .merge(TestPassage.where("test_passages.created_at > ?", last_award_date))
через знак вопроса обещали убрать возможность подстановки аргумента в будущих апдейтах рельс
оставят подстановку по ключу
```ruby
.where("test_passages.created_at > :date, date: last_award_date)
```

2020-08-20 04:51 UTC, max-underthesun commented on app/views/admin/badges/_form.html.erb
> +      <%= f.select :rule_name, t("badge.rule_name.").invert, {}, { class: 'form-control' } %>
1. не нашел ключей `badge` и `rule_name` в файлах локализации
2. лучше в "селекте" опираться на тот же источник, что и в валидации в модели, там я порекомендовал ссылаться на константу, которую нужно добавить в сервис (почти всегда нужно стараться, чтобы был один `source of truth`, чтобы не получить потом лишние проблемы, когда надо будет править одно и то же в нескольких точках в коде и что-то пойдет не так)

2020-08-20 04:51 UTC, max-underthesun commented on app/controllers/test_passages_controller.rb
> +    session[:urls] = awarded_badges&.pluck(:url)
а это зачем? не вижу использования

2020-08-25 04:31 UTC, max-underthesun reviewed
мне кажется ты проигнорировал часть моих комментариев с прошлого раза
и по обновленному коду тоже есть вопросы

2020-08-25 04:31 UTC, max-underthesun commented on app/models/user.rb
> +  has_many :badges_users, dependent: :delete_all
писал в прошлый раз про `delete_all`

2020-08-25 04:31 UTC, max-underthesun commented on app/services/awarder.rb
> +  def user_badge_awards(badge)
посмотри на вызовы этого метода и подумай в чем ошибка
можно еще почитать мои предыдущие комменты, там все рассказано

2020-08-25 04:31 UTC, max-underthesun commented on app/services/awarder.rb
> +                       end
вот этот код здесь выглядит так себе, читать неудобно
к тому же часть кода повторяется в разных проверках
хорошо бы вынести это в отдельные методы
вместо мерджа точно можно либо метод написать, либо скоуп в модели, мержд 100% дублируется

2020-08-28 14:42 UTC, max-underthesun commented on app/views/test_passages/result.html.erb
> +  <% current_user.badges << awarded_badges %>
ну почему во вьюхе то????
вьюхи - это рендеринг
зачем в них операции с объектами производить
у тебя было в экшене контроллера, я предложил в другой экшен контроллера перенести, более подходящий
а ты во вьюху перенес...
в контроллер вручение наград!!!

2020-08-28 14:42 UTC, max-underthesun commented on app/services/awarder.rb
> +  def user_badge_awards(badge)
еще раз: https://github.com/mymadhead/testGuru/pull/34/files#r476153242

2020-08-28 14:42 UTC, max-underthesun commented on app/views/admin/badges/_form.html.erb
> +      <%= f.select :rule_name, t("badge.rule_name").invert, {}, { class: 'form-control' } %>
посмотри пожалуйста комментарий из первого ревью: https://github.com/mymadhead/testGuru/pull/34#discussion_r473585135

2020-08-28 14:44 UTC, mymadhead commented on app/views/test_passages/result.html.erb
> +  <% current_user.badges << awarded_badges %>
🤦‍♂️я не знаю зачем его туда всунул) переделываю!

2020-08-28 14:45 UTC, mymadhead commented on app/views/admin/badges/_form.html.erb
> +      <%= f.select :rule_name, t("badge.rule_name").invert, {}, { class: 'form-control' } %>
исправляю!

2020-09-06 12:23 UTC, max-underthesun commented on app/controllers/test_passages_controller.rb
> +    if @test_passage.completed?
а в этот экшен вроде как именно по этому условию и редиректит - посмотри код экшена `update`
зачем здесь повторно то же самое проверять?

2020-09-06 12:23 UTC, max-underthesun commented on app/views/admin/badges/_form.html.erb
> +      <%= f.select :rule_name, Awarder::RULES, {}, { class: 'form-control' } %>
хорошо, что ты ссылаешься на коллекцию "возожмных правил", но
здесь точно не помешала бы локализация
более верный подход - хранить или динамически создавать нужные для вьюхи коллекции (для метода селект) в хелперах
чтобы во вьюхе остался только вызов такого хелпера
типа:
```haml
<%= f.select :rule, options_for_select(badge_rules) ... %>
```
при этом конечно же будет правильно выводить в селекте не те имена, которые хранятся в константе в классе, а локализованные тексты
т.е. нужно собирать коллекцию имен правил с локализованными текстами в хелпере на основании коллекции правил из модели и файла локализации

итоговая коллекция, которая передается в селект может выглядеть как-то так:
```ruby
[
  ['Complete all tests in category', :category],
  [...],
  ...
]
```
соответсвенно хелпер нужно реализовать так, чтобы он опирался на константу со списком правил из класса, но при этом возвращал коллекцию в описанном выше виде

2020-09-06 12:23 UTC, max-underthesun commented on app/services/awarder.rb
> +  def user_badge_awards(badge)
ну я не знаю как еще здесь прокомментировать )))
еще раз
посмотри на эту строку `def user_badge_awards(badge)`, посмотри на код этого метода, посмотри как ты этот метод вызываешь
ошибка очень простая, но при этом с ней код просто не рабочий
если ты не видишь ошибку, то я не знаю что и думать
мне в голову приходят пока следующие мысли:
1. ты не проверял работу кода
2. ты не понимаешь код, который у тебя написан
3. оба предыдущих варианта

и любой из этих варианто - это не очень правильно

2020-11-06 12:58 UTC, VidgarVii commented on app/models/test_passage.rb
> +    correct_answers.ids.sort == answer_ids.map(&:to_i).sort unless answer_ids.nil?
выбирай способ более читабельней 
correct_answers.ids.sort == answer_ids&.map(&:to_i)&.sort
answer_ids && correct_answers.ids.sort == answer_ids.map(&:to_i).sort
answer_ids && (correct_answers.ids - answer_ids.map(&:to_i)).empty?
return false if answer_ids
correct_answers.ids.sort == ....

2020-11-06 15:29 UTC, VidgarVii commented on app/views/test_passages/result.html.erb
> +<%= session[:badges].each do |badge_details|  %>
следи за отступами.

В `<%=` тут `=` лишний

2020-11-06 15:38 UTC, VidgarVii commented on app/services/awarder.rb
> +  def first_try(_rule_value)
Если этот тип награды не учитывает rule_value, то зачем требовать его наличия при создании?

2020-11-06 15:38 UTC, VidgarVii commented on app/views/admin/badges/_form.html.erb
> +    <%= f.submit t('.submit'), class: "btn btn-primary mt-3" %>
ленивая локализация не настроена

2020-11-06 15:57 UTC, VidgarVii commented on app/views/admin/badges/index.html.erb
> +
таги таблицы надо оборачивать в тег <table>

2020-11-06 15:57 UTC, VidgarVii commented on app/assets/stylesheets/badges.scss
> +}
не подключен файл. 
нет пустой строки в конце файла

2020-11-06 17:57 UTC, VidgarVii requested changes

2020-11-06 17:57 UTC, VidgarVii commented on app/models/badge.rb
> +  validates :rule_value, presence: true, uniqueness: { scope: :rule_value }
некорректная валидация

2020-11-06 17:59 UTC, VidgarVii commented
merge AR конечно интересная практика. так ОРМ умный и сам строит для нас почти всегда верный запрос в БД, мы можем себе позволить подобные слияния и переопределения начального скоупа. Но на больших запросах например, если придется писать какой нить QueryObject то этот merge может с играть злую шутку с оперативной памятью.

2020-11-07 09:52 UTC, VidgarVii requested changes

2020-11-07 09:52 UTC, VidgarVii commented on app/views/test_passages/result.html.erb
> +<% if session[:badges].any? %>
лучше из базы тащить информацию о наградах. Как правило часто информацию о сессии хранят в браузере пользователя. Он решит почистить браузер и потом увидит, что все награды пропали. Не хорошо получиться. 
Использование сессий тут сомнительна.

2020-11-09 16:00 UTC, VidgarVii commented on app/services/awarder.rb
> +    user_loser_tests = @user.tests.merge(TestPassage.where.not(success: true))
TestPassage.where(success: false)

2020-11-09 16:15 UTC, VidgarVii commented on app/services/awarder.rb
> +end
В классе Awarder все методы для проверки выдавать ли награду возвращают булевое значение. Значит предикаты. Для предикатов есть отдельный синтаксис. В конце названия метода добавляем знак "?"
Соответственно название метода должно быть соответствующие. 
```
give_loser_award?
give_category_award?
и пр.
```
Так увеличиться читабельностьВ классе Awarder все методы для проверки выдавать ли награду возвращают булевое значение. Значит предикаты. Для предикатов есть отдельный синтаксис. В конце названия метода добавляем знак "?"
Соответственно название метода должно быть соответствующие. 
```
give_loser_award?
give_category_award?
и пр.
```
Так увеличиться читабельность

2020-11-09 16:15 UTC, VidgarVii commented on app/services/awarder.rb
> +                       end
```
user_level_tests =
  if last_award_date.present?
    user_successful_tests
      .where(category_id: @test.category.id)
      .merge(TestPassage.where('test_passages.created_at' > :date, date: last_award_date))
  else
    user_successful_tests.where(category_id: @test.category.id)
  end
```

2020-11-09 16:15 UTC, VidgarVii commented on app/services/awarder.rb
> +    user_loser_tests = @user.tests.merge(TestPassage.where.not(success: true))
вообще для получения верно пройденных тестов у юзера уже есть скоуп. Почему ты им не пользуешься?

2020-11-09 16:20 UTC, VidgarVii requested changes

2020-11-09 16:20 UTC, VidgarVii commented on app/services/awarder.rb
> +    user_loser_tests = @user.tests.merge(TestPassage.where.not(success: true))
Кстати у тебя user_loser_tests всегда будет содержать пустой Relation, так как в TestPassage#accept! баг

2020-11-09 16:41 UTC, max-underthesun reviewed
вот такой был комментарий довольно важный давно мной оставлен, но исправления не вижу: https://github.com/mymadhead/testGuru/pull/34/files#r473581645

вот еще один уже древний коммент, тоже важный: https://github.com/mymadhead/testGuru/pull/34/files#r484062679

и вот еще Павел от тебя пытается дождаться исправления: https://github.com/mymadhead/testGuru/pull/34/files#r519159552 - повтори тему контроллеров, вспомни как из контроллера во вью можно (и нужно) передавать данные без использования сессии (недостаток сессии Павел описал)

2020-11-09 16:41 UTC, max-underthesun commented on app/services/awarder.rb
> +                       end
вот этот "лапшевидный" код это конечно не лучшее, что можно сотворить своими руками... настаивать наверное не буду, но вряд ли тебя похвалят, если ты такое будешь в рабочем проекте выдавать
(аналогичные фрагменты есть не только здесь)

2020-11-10 05:24 UTC, VidgarVii requested changes

2020-11-10 05:24 UTC, VidgarVii commented on app/services/awarder.rb
> +    user_loser_tests = @user.tests.merge(TestPassage.where.not(success: true))
У юзера есть связь для получения пройденных тестов, А у TestPassage скоуп. Почему ты ими не пользуешься?

2021-03-29 10:33 UTC, merged